### PR TITLE
Modernized node-vips

### PR DESCRIPTION
**Pull request by jValdron**
Works with newer versions of VIPS, doesn't use the libjpeg shrink on read feature though.

Also uses GYP for building the package now.

### CODE REVIEW

**Comment by c4milo** [comment]
@jValdron nice work. I hope @dosx can merge this soon.

**Comment by eden** [comment]
Thanks @jValdron. We'll merge this in soon. In the meantime can you squash this together into one commit?

**Comment by epoberezkin** [comment]
When do you think it will be merged?

**Comment by eden** [comment]
Thanks @jValdron I've squashed your commits and pushed.

**Comment by epoberezkin** [comment]
Thanks @jValdron and @eden, timing couldn't have been better

**Pull request closed without merging**
